services:
  database:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234=1234
    ports:
      - "5432:5432"
    volumes:
      - ../storage/database:/var/lib/postgresql/data
    restart: unless-stopped

  file-storage:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - AWS_ACCESS_KEY_ID=devprepaccesskey
      - AWS_SECRET_ACCESS_KEY=devprepsecretkey
    ports:
      - "9333:9333" # Master server (admin UI at http://localhost:9333)
      - "8080:8080" # Volume server
      - "8888:8888" # Filer server (file browser UI)
      - "23646:23646" # S3 API server
      - "8333:8333" # gRPC server
    volumes:
      - ../storage/files:/data
    command: ["mini", "-dir=/data"]
